# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Food-Truck-TrackR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Food-Truck-TrackR

  pod 'Firebase'
  pod 'Firebase/Auth'


  target 'Food-Truck-TrackRTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
